# Program Description

# This file should be placed within a directory that only contains node
# files generated by gatherData.py.  This file will create two files
# name public_rounds.txt and private_rounds.txt that will hold the
# round info to be used as input to part2.py and part3.py.

import sys
import os

if __name__ == "__main__":
    public_rounds = []
    private_rounds = []
    firstFile = True

    # Keep track of how many ACKs per round (first 16 public, last 16 private)
    ack = 0
    prev = ""

    for r in range(0, 120):
        public_rounds.append(({}, {}))
        private_rounds.append(({},{}))

    for filename in os.listdir('.'):
        if(filename).endswith(".txt"):
            
            with open(filename) as f:
                lines = f.readlines()
                prev = ""
            
                start = 0
                #print("Start")
                while(True):
                    #print(lines[start])
                    items = lines[start].rstrip().split(' ')
                    if(items[1] == "OFFER"):
                        if(prev == "ACK"):
                            break
                        prev = "OFFER"
                    else:
                        prev = "ACK"
                    start += 1
                
                finish = 0
                lines.reverse()
                prev = ""
                #print("Finish")
                while(True):
                    #print(lines[finish])
                    items = lines[finish].rstrip().split(' ')
                    if(items[1] == "OFFER"):
                        prev = "OFFER"
                    else:
                        prev = "ACK"
                        break
                    finish += 1
                finish = len(lines) - finish

                # traverse directory to batch 2
                os.chdir("../batch2")

                #print("Start: {}     Finish: {}".format(start,finish))
                lines.reverse()
                count = 0
                with open(filename, "a") as f2:
                    for i in range(start,finish):
                        count += 1
                        #print(count)
                        f2.write(lines[i])

                # traverse back to batch 3
                os.chdir("../batch3")
                #print('\n')
















